# Generated by Django 4.2.30 on 2026-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup_menulinks_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/imagens/%Y/%m/%d'),
        ),
    ]
