# Generated by Django 4.2.30 on 2026-10-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/favicon/%Y/%m/%d'),
        ),
    ]
